---
kubectl_install_become: false
kubectl_install_method: "{{ yake_install_method | default('binary') }}"
kubectl_install_container_registry: ghcr.io
kubectl_install_container_image: yakecloud/kubectl
# renovate: datasource=docker depName=ghcr.io/yakecloud/kubectl
kubectl_install_version: 'v1.33.8'
kubectl_install_uid: "{{ ansible_facts.user_uid | string }}"
kubectl_install_gid: "{{ ansible_facts.user_gid | string }}"
kubectl_install_proxy_env: "{{ proxy_env | default({}) }}"
