---
clusterapi_install_become: false
clusterapi_install_infrastructure: openstack
clusterapi_install_clusterapi_name: clusterapi
clusterapi_install_cluster_topology: true
clusterapi_install_uid: "{{ ansible_facts.user_uid | string }}"
clusterapi_install_gid: "{{ ansible_facts.user_gid | string }}"
