---
clusterctl_install_become: false
clusterctl_install_method: "{{ yake_install_method | default('binary') }}"
clusterctl_install_container_registry: ghcr.io
clusterctl_install_container_image: yakecloud/clusterctl
# renovate: datasource=docker depName=ghcr.io/yakecloud/clusterctl
clusterctl_install_version: 'v1.12.2'
clusterctl_install_uid: "{{ ansible_facts.user_uid | string }}"
clusterctl_install_gid: "{{ ansible_facts.user_gid | string }}"
